model: openrouter/google/gemini-2.5-pro-exp-03-25
editor-model: openrouter/google/gemini-2.5-pro-exp-03-25
weak-model: gemini/gemini-2.0-flash-exp
edit-format: udiff
editor-edit-format: udiff
max-chat-history-tokens: 1000000
map-tokens: 3000
chat-language: English
cache-prompts: true
map-refresh: always
watch-files: true
verbose: true
read:
  - AiderGuidelines.md