model: gemini/gemini-2.5-pro
editor-model: gemini/gemini-2.5-pro
weak-model: gemini/gemini-2.5-flash
edit-format: udiff
editor-edit-format: udiff
max-chat-history-tokens: 1000000
map-tokens: 3000
chat-language: English
cache-prompts: true
map-refresh: always
watch-files: true
verbose: true
read:
  - AiderGuidelines.md